<?php

declare(strict_types=1);

/*
 * AuthLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AuthLib\Models;

class TypesEnum
{
    public const USERPROFILE = 'user/profile';

    public const PROPERTYBILLINGCOMPANYALL = 'property/billing-company/all';
}
